-- Generated by HyprMod

-- Environment
hl.env("XCURSOR_THEME", "catppuccin-mocha-dark-cursors")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_THEME", "catppuccin-mocha-dark-cursors")
hl.env("HYPRCURSOR_SIZE", "24")

-- Settings
hl.config({
    general = {
        hover_icon_on_border = true,
        resize_on_border = true,
    },
})

-- Layer rules
hl.layer_rule({
    name = "rofi",
    match = {
        namespace = "rofi",
    },
    dim_around = true,
})
