wallpaper {
    monitor = eDP-1
    path = ~/Imagens/wallpapers/a_snowy_mountain_tops.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/Imagens/wallpapers/a_snowy_mountain_tops.jpg
    fit_mode = cover
}
