wallpaper {
    monitor = eDP-1
    path = ~/dotfiles/wallpapers/a_field_of_grass_at_night.jpeg
    fit_mode = cover
}

wallpaper {
    monitor = DP-1
    path = ~/dotfiles/wallpapers/blackhole.jpg
    fit_mode = cover
}
