#!/usr/bin/env bash
#
# Adjust screen brightness for internal and external monitors, sending a notification
#
# Requires: brightnessctl, ddcutil
# Author: Jesse Mirabel (Modified for dual-monitor support)

DEF_VALUE=5

usage() {
  local script=${0##*/}
  cat <<-EOF
        USAGE: $script {up|down} [value]

        OPTIONS:
          up   [value]    Increase brightness by [value] (default: $DEF_VALUE)
          down [value]    Decrease brightness by [value] (default: $DEF_VALUE)
EOF
}

main() {
  local action=$1
  local value=${2:-$DEF_VALUE}

  if ((value < 1)); then
    usage >&2
    return 1
  fi

  case $action in
  up | down)
    local sign ddc_action
    case $action in
    up)
      sign='+'
      ddc_action="+"
      ;;
    down)
      sign='-'
      ddc_action="-"
      ;;
    esac

    brightnessctl -n set "${value}%${sign}" >/dev/null

    if command -v ddcutil &>/dev/null; then
      ddcutil setvcp 10 "$ddc_action" "$value" &>/dev/null &
    fi

    local level
    level=$(brightnessctl -m | awk -F ',' '{print $4}' | tr -d '%')

    notify-send "Brilho: ${level}%" -h int:value:"$level" -i \
      "contrast" -h string:x-canonical-private-synchronous:backlight
    ;;
  *)
    usage >&2
    return 1
    ;;
  esac
}

main "$@"
